"""
Full NAV dump to a multi-sheet Excel workbook.

This is the COMPLETE local dataset (every index, every date) — distinct from the
per-chart CSV (which exports only what's currently plotted). Intended as a general
NSE-index data source for other analysis.

Layout:
  * "All NAV"            -> every local index (Date + all columns).
  * one sheet per NSE category (Broad market / Sector-thematic / Factor /
    Fixed income-debt / REIT-InvIT) with just that category's indices.
  * "About"             -> source file, as-of, coverage.

Values are total-return index LEVELS (the same numbers the engine loads); dates
are real Excel dates (yyyy-mm-dd).
"""
from __future__ import annotations

import io
import pandas as pd

from . import data, catalog

CATEGORY_ORDER = ["Broad market", "Sector / thematic", "Factor",
                  "Fixed income / debt", "REIT / InvIT"]


def _sheet(name: str) -> str:
    """Excel-safe sheet name (no / \\ ? * [ ] :, <=31 chars)."""
    for ch in '/\\?*[]:':
        name = name.replace(ch, "-")
    return name[:31]


def build_nav_workbook():
    """Return (BytesIO xlsx, filename) of the full multi-sheet NAV dump."""
    df = data.load().copy()
    df.index.name = "Date"
    asof = data.asof()
    groups = {c: catalog._group(c) for c in df.columns}

    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter",
                        date_format="yyyy-mm-dd", datetime_format="yyyy-mm-dd") as xw:
        # 1) consolidated — all indices
        df.reset_index().to_excel(xw, sheet_name="All NAV", index=False)
        # 2) one sheet per NSE category (known order first, then any extras)
        cats = CATEGORY_ORDER + sorted(set(groups.values()) - set(CATEGORY_ORDER))
        done = set()
        for grp in cats:
            if grp in done:
                continue
            done.add(grp)
            cols = [c for c in df.columns if groups[c] == grp]
            if cols:
                df[cols].reset_index().to_excel(xw, sheet_name=_sheet(grp), index=False)
        # 3) about / provenance
        about = pd.DataFrame({
            "Field": ["Source file", "Data as of", "Total indices", "Date range",
                      "Values", "Generated by"],
            "Value": [data.source_filename(), str(asof), int(df.shape[1]),
                      f"{df.index.min().date()} .. {df.index.max().date()}",
                      "Total-return index levels (NAV)", "Vistas passive terminal"],
        })
        about.to_excel(xw, sheet_name="About", index=False)

    buf.seek(0)
    fname = f"Vistas_NSE_NAV_{str(asof).replace(',', '').replace(' ', '_')}.xlsx"
    return buf, fname
